version: '3.4'

services:
  webestudofront:
    image: webestudofront
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:80
